### PR TITLE
Osx macports gcc5

### PR DESCRIPTION
**Pull request by piyushrpt**
This pull request addressed two issues. Tested on OS-X 10.11.4 with gcc5 from macports. All the other libraries like pcre, xerces, fftw3 are from macports.

The line used for configuration:
```bash
PYTHON=/opt/local/bin/python3 PYTHON_CONFIG=/opt/local/bin/python3.5-config python3 waf configure --prefix=/Users/agram/packages/MDA/install --with-cxxflags="-I /opt/local/include" --with-cflags="-I /opt/local/include" --with-linkflags="-L/opt/local/lib" --disable-swig
```

csm still breaks on OS-X and explicit changes are needed to VTS to get this to work.

1) Changes to build/build.py need to build six:
   - sys_platform returns "darwin"
   - libnsl is not needed for darwin
   - -Wl,-E option for ld is not supported on darwin

2) Fixes a bunch of ambiguous casts to size_t in "six.sicd/source/SICDWriteControl.cpp" and "six/source/NITFWriteControl.cpp" for size_t. Use nitf::Uint64 instead.

### CODE REVIEW

File: six/modules/c++/six.sicd/source/SICDWriteControl.cpp [hunk 1]
```diff
@@ -103,10 +103,10 @@ void SICDWriteControl::writeHeaders()
         //       SIDD as you will have some pad
         // TODO: Would be nice if ImageSubheader had a method to compute this
         //       for you
-        const size_t numRows(subheader.getNumRows());
-        const size_t numCols(subheader.getNumCols());
-        numBands = subheader.getNumImageBands();
-        const size_t numBitsPerPixel(subheader.getNumBitsPerPixel());
+        const size_t numRows(static_cast<nitf::Uint64>(subheader.getNumRows()));
```
Comment (asylvest) [inline six/modules/c++/six.sicd/source/SICDWriteControl.cpp]: Ahh I see... so for both these cases (which is coming from the nitf module's `Field.hpp`) and the below cases (coming from six's `Parameter.h`) the OSX compiler isn't finding a cast operator that's exactly for `size_t` and is complaining.  It's easy enough to add a cast operator for `size_t` to those two classes so that you wouldn't need these casts here, but I'm not sure if that'll compile on OS's where `nitf::Uint64` and `size_t` are the exact same underlying type (rather than just unsigned ints of the same size)... if I remember correctly, they're the exact same type on Windows (I've had annoyances related to this in the past).

If it comes to it, we can live with the casts if we really need to but I'll see if there's another way.

**Comment by piyushrpt** [comment]
I also figured the changes needed to coda's build/build.py to compile python bindings successfully on OS X. You should be able to see this in a separate commit.

**Comment by ayoungs** [comment]
I'm trying to go a big leap and compile on latest mac osx (10.13 High Sierra).
The build.py needs one other thing (clang based llvm compiler) -m64 is not longer recognized, so it things it's 32bit, I just make a separate section for r'darwin' and that solves that.
The change for dylib above fixed the other issue.
I'm now stuck on test_sidd_blocking.cpp
    std::string testPathname = str::toString(sys::Path(installPathname).
        join("bin").join(programName));
It's not liking the <<  of sys::Path(installPathname)
It's probably a minor edit, it is eluding me.

**Comment by asylvest** [comment]
Can you paste in the compiler error you're getting for sys::Path?

**Comment by ayoungs** [comment]
In file included from ../six/modules/c++/six.sidd/tests/test_sidd_blocking.cpp:25:
In file included from /Users/ayoungs/Documents/swdev/six-library-osx/six-library/externals/coda-oss/modules/c++/io/include/io/TempFile.h:27:
In file included from /Users/ayoungs/Documents/swdev/six-library-osx/six-library/externals/coda-oss/modules/c++/sys/include/sys/OS.h:27:
In file included from /Users/ayoungs/Documents/swdev/six-library-osx/six-library/externals/coda-oss/modules/c++/sys/include/sys/AbstractOS.h:28:
In file included from /Users/ayoungs/Documents/swdev/six-library-osx/six-library/externals/coda-oss/modules/c++/sys/include/sys/Conf.h:27:
/Users/ayoungs/Documents/swdev/six-library-osx/six-library/externals/coda-oss/modules/c++/str/include/str/Convert.h:49:27: error: call to function 'operator<<' that is neither visible in the template definition nor found by argument-dependent lookup
    buf << std::boolalpha << value;
                          ^
../six/modules/c++/six.sidd/tests/test_sidd_blocking.cpp:75:37: note: in instantiation of function template specialization 'str::toString<sys::Path>' requested here
    std::string testPathname = str::toString(sys::Path(installPathname).
                                    ^
/Users/ayoungs/Documents/swdev/six-library-osx/six-library/externals/coda-oss/modules/c++/sys/include/sys/Path.h:278:15: note: 'operator<<' should be declared prior to the call site or in namespace 'sys'
std::ostream& operator<<(std::ostream& os, const sys::Path& path);

Thanks!
I’ve got this vision of eventually using Apple’s ARKit with SAR data for some reason, and six library will get me there.

Best regards,

Andy

**Comment by ayoungs** [comment]
Found the problem the operator << is declared in 3 headers outside the namespace  Path.h, Trace.h and Throwable.h move it just inside the final }

**Comment by ayoungs** [comment]
Any way to disable the csm stuff? when I put in --disable-csm the script chokes

**Comment by asylvest** [comment]
For now the easiest thing is probably to just target specifically what you want (i.e. `waf install --target=six.sicd-c++`).  I am hoping to have some time over the next week to take a look at this branch and have you guys test it out to verify everything works since I don't have a Mac to test.

What is the error you get when using `--disable-csm`?

**Comment by piyushrpt** [comment]
I had the same problem. It would barf with "--disable-csm" as well. Instead I got it work by making the following csm related changes. I had to modify the code files and then zip it up again since waf appears to unzip each time.

#23 
1. Replace "termio.h" with "termios.h" in vts_misc.cpp under vts_301_0

2. Map a bunch of things in vts_isd.cpp using define

```c++
#define ftello64 ftello
#define fseeko64 fseeko
#define fopen64 fopen
#define fsetpos64 fsetpos
#define off64_t off_t
#define fpos64_t fpos_t
```

3. Modify six/projects/csm/wscript. Needed linking to libcsmapi.
```python
@@ -68,7 +68,7 @@ def build(bld):
         modArgs = globals()
         modArgs['NAME'] = name
         modArgs['LIBNAME'] = name
-        if re.match(r'win32', sys.platform):
+        if re.match(r'win32', sys.platform) or re.match(r'darwin', sys.platform):
             modArgs['USE'] = 'CSMAPI'
         else:
             modArgs['INCLUDES'] = ['include', bld.env['INCLUDES_CSM']]
```

**Comment by ayoungs** [comment]
Aww #3 was what I was missing.  I had figure 1 and 2 out. Thank you!

**Comment by ayoungs** [comment]
Compiles and installs great, this is latest High Sierra 10.13!

**Comment by ayoungs** [comment]
Just a check on --disable-csm now. If one does that it would cause errors:
[545/787] cxx: modules/c++/six.sidd/source/DerivedClassification.cpp -> 
../six/projects/csm/source/SIDDSensorModel.cpp:23:10: fatal error: 'Error.h' file not found
#include "Error.h"
         ^~~~~~~~~
1 error generated.
../six/projects/csm/source/SIXSensorModel.cpp:26:10: fatal error: 'Error.h' file not found
#include "Error.h"
         ^~~~~~~~~
1 error generated.
In file included from ../six/projects/csm/source/SIXPlugin.cpp:27:
/Users/ayoungs/Documents/swdev/six-library-osx/six-library/six/projects/csm/include/six/csm/SIXPlugin.h:34:10: fatal error: 'Plugin.h' file not found
#include "Plugin.h"

../six/projects/csm/source/SICDSensorModel.cpp:23:10: fatal error: 'Error.h' file not found
#include "Error.h"
         ^~~~~~~~~

and ../six/projects/csm/tests/test_sidd_csm.cpp:34:10: fatal error: 'RasterGM.h' file not found
#include <RasterGM.h>
In file included from ../six/projects/csm/tests/test_sicd_csm.cpp:31:
../six/projects/csm/tests/utilities.h:24:10: fatal error: 'NitfIsd.h' file not found
#include <NitfIsd.h>

It compiles without the --disable-csm so I'm good to go, but for sake of completeness I provided the errors when --disable-csm is added (with fix to wscript of item 3: Modify six/projects/csm/wscript. Needed linking to libcsmapi.).

**Comment by ayoungs** [comment]
Rebuilding with the latest master.
I could build in July with the above fixes.
However, now I cannot.
I get:
Undefined symbols for architecture x86_64:
  "except::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, except::Trace const&)", referenced from:
      except::Throwable::toString() const in test_extract_xml.cpp.13.o
      except::Throwable::toString() const in libio-c++.1.0.a(FileOutputStreamOS.cpp.1.o)
      except::Throwable::toString() const in libcli-c++.1.2.a(ArgumentParser.cpp.1.o)
      except::Throwable::toString() const in libcli-c++.1.2.a(Argument.cpp.1.o)
      except::Throwable::toString() const in libstr-c++.1.0.a(Convert.cpp.1.o)
      except::Throwable::toString() const in libsys-c++.1.2.a(MutexPosix.cpp.1.o)
      except::Throwable::toString() const in libsys-c++.1.2.a(LocalDateTime.cpp.1.o)
      ...
ld: symbol(s) not found for architecture x86_64
I checked the .o files they're all similar to:
target/externals/coda-oss/modules/c++/io/source/InputStream.cpp.1.o: Mach-O 64-bit object x86_64

clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
ld: warning: ld: warning: ld: warning: ignoring file externals/coda-oss/modules/c++/logging/liblogging-c++.1.1.a, file was built for archive which is not the architecture being linked (i386): externals/coda-oss/modules/c++/logging/liblogging-c++.1.1.aignoring file externals/coda-oss/modules/c++/io/libio-c++.1.0.a, file was built for archive which is not the architecture being linked (i386): externals/coda-oss/modules/c++/io/libio-c++.1.0.aignoring file externals/coda-oss/modules/c++/mt/libmt-c++.1.1.a, file was built for archive which is not the architecture being linked (i386): externals/coda-oss/modules/c++/mt/libmt-c++.1.1.a


ld: warning: ignoring file externals/coda-oss/modules/c++/str/libstr-c++.1.0.a, file was built for archive which is not the architecture being linked (i386): externals/coda-oss/modules/c++/str/libstr-c++.1.0.a
ld: warning: ignoring file externals/coda-oss/modules/c++/sys/libsys-c++.1.2.a, file was built for archive which is not the architecture being linked (i386): externals/coda-oss/modules/c++/sys/libsys-c++.1.2.a
ld: warning: ignoring file externals/coda-oss/modules/c++/except/libexcept-c++.1.0.a, file was built for archive which is not the architecture being linked (i386): externals/coda-oss/modules/c++/except/libexcept-c++.1.0.a

uname -p
i386
uname -a at the very end is
_x86_64 x86_64

I pulled down a new config.guess from gnu.org, that didn't help.
What am I missing?

**Comment by ayoungs** [comment]
It turns out it appears
"except::operator<<(std::__1::basic_ostream<char, std::__1::char_traits >&, except::Trace const&)", 
Is the last problem.  Again with the header placement of that.

Then a tweak may need to be made to have import/except.h included in a few files.
There's some wscript problem that's not allowing test_extract_xml to link.
I'm not fluent enough with waf to debug this in any reasonable sort of time.

**Comment by ayoungs** [comment]
This feels like it's similar to past issues -- that have been fixed due to namespace and compiler peculiarities from platform to platform.

**Comment by asylvest** [comment]
If you include `<ostream>` in `Trace.h` and `Context.h` does it resolve the problem?  Is this a compiler or linker error?

**Comment by ayoungs** [comment]
Linker error.  Even with the #include <ostream> added, it’s still having the same error.

[780/853] cxxprogram: ../target/six/modules/c++/samples/test_extract_xml.cpp.14.o -> ../target/six/modules/c++/samples/test_extract_xml
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
Undefined symbols for architecture x86_64:
  "except::operator<<(std::ostream&, except::Trace const&)", referenced from:
      except::Throwable::toString() const in test_extract_xml.cpp.14.o
      except::Throwable::toString() const in libio-c++.1.0.a(FileOutputStreamOS.cpp.1.o)
      except::Throwable::toString() const in libcli-c++.1.2.a(ArgumentParser.cpp.1.o)
      except::Throwable::toString() const in libcli-c++.1.2.a(Argument.cpp.1.o)
      except::Throwable::toString() const in libstr-c++.1.0.a(Convert.cpp.1.o)
      except::Throwable::toString() const in libsys-c++.1.2.a(MutexPosix.cpp.1.o)
      except::Throwable::toString() const in libsys-c++.1.2.a(LocalDateTime.cpp.1.o)


Best regards,

Andy

**Comment by ayoungs** [comment]
This is probably the problem though.
I see Throwable.h

    virtual std::string toString() const
    {
        std::ostringstream s;
        s << getType() << ": " << getMessage();

        const except::Trace& t = getTrace();
        if (t.getSize() > 0)
            s << ": " << t;
        return s.str();
    }

And Trace.h

std::ostream& operator<<(std::ostream& os, const except::Trace& t);


Above s being a std::ostringstream and the Trace operator to ostream.

Could be the particulars of compiler.

clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]

Looks like that’s likely an issue.
The build.py will need further tweaking, any hints on changing that to clang for macOS?

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Andys-MBP:six-library andyyoungs$ clang --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Andys-MBP:six-library andyyoungs$ clang++ --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Andys-MBP:six-library andyyoungs$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

It’s have to have clang and clang++ I presume?

Best regards,

Andy

**Comment by asylvest** [comment]
Those lines look ok to me - ostringstream inherits from ostream.  It seems like your linker is not finding the implementation of except::Trace's ostream operator.  Is it really compiling Trace.cpp?  In your post in June, you indicated moving those operators inside the namespace.  That should not be required... do you have a local change where you moved it inside the namespace in the header but not in the cpp?

**Comment by ayoungs** [comment]
I’ll look at it again on 20th.
I had a local copy where I moved it inside the header.
Aww I bet it’s not seeing it due to namespace.  It is compiling the file.

Thanks!

Andy

**Comment by ayoungs** [comment]
Stepping back to a fresh clone.
Based on the comment that I shouldn't have to tweak headers I left everything pristine, except the following:
Fixing the build.py as in top of this comment section.

Fixing CSM vts_misc.cpp and vts_isd.cpp per above comments.

The initial errors:

/Users/andyyoungs/Documents/swdev/six-library-osx/six-library/externals/coda-oss/modules/c++/str/include/str/Convert.h:49:27: error: call to function 'operator<<' that is neither visible in the template definition nor found by argument-dependent lookup
    buf << std::boolalpha << value;
                          ^
../six/modules/c++/six.sidd/tests/test_sidd_blocking.cpp:75:37: note: in instantiation of function template specialization 'str::toString<sys::Path>' requested here
    std::string testPathname = str::toString(sys::Path(installPathname).
                                    ^
/Users/andyyoungs/Documents/swdev/six-library-osx/six-library/externals/coda-oss/modules/c++/sys/include/sys/Path.h:278:15: note: 'operator<<' should be declared prior to the call site or in namespace 'sys'
std::ostream& operator<<(std::ostream& os, const sys::Path& path);


It's like namespace conflicts get in the way.  The only way to get past this is moving std::ostream& operator<<(std::ostream& os, const sys::Path& path);  inside the namespace.

Which was suggested shouldn't need to happen, the specifics of gcc/g++

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

 $g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by asylvest** [comment]
#221 should fix the `--disable-csm` issue
https://github.com/mdaus/coda-oss/pull/244 should fix the ostream operator issue
Just need one more fix for build.py

**Comment by ayoungs** [comment]
Once I get coda-oss going, then I can get the build far enough to test the other.

Great work getting it there!

**Comment by ayoungs** [comment]
[682/873] cxx: modules/c++/tiff/source/FileReader.cpp -> target/modules/c++/tiff/source/FileReader.cpp.1.o
../modules/c++/logging/unittests/test_exception_logger.cpp:64:29: error: expected ';' after expression
    mt::GenerationThreadPool pool(numThreads);
                            ^
                            ;
../modules/c++/logging/unittests/test_exception_logger.cpp:64:9: error: no member named 'GenerationThreadPool' in namespace 'mt'
    mt::GenerationThreadPool pool(numThreads);
    ~~~~^
../modules/c++/logging/unittests/test_exception_logger.cpp:64:30: error: use of undeclared identifier 'pool'
    mt::GenerationThreadPool pool(numThreads);
                             ^
../modules/c++/logging/unittests/test_exception_logger.cpp:65:5: error: use of undeclared identifier 'pool'; did you mean 'powl'?
    pool.start();
    ^~~~
    powl
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/math.h:444:20: note: 'powl' declared here
extern long double powl(long double, long double);
                   ^
../modules/c++/logging/unittests/test_exception_logger.cpp:65:9: error: member reference base type 'long double (long double, long double)' is not a structure or union
    pool.start();
    ~~~~^~~~~~
../modules/c++/logging/unittests/test_exception_logger.cpp:68:5: error: use of undeclared identifier 'pool'; did you mean 'powl'?
    pool.addAndWaitGroup(runs);
    ^~~~
    powl
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/math.h:444:20: note: 'powl' declared here
extern long double powl(long double, long double);
                   ^
../modules/c++/logging/unittests/test_exception_logger.cpp:68:9: error: member reference base type 'long double (long double, long double)' is not a structure or union
    pool.addAndWaitGroup(runs);
    ~~~~^~~~~~~~~~~~~~~~
../modules/c++/logging/unittests/test_exception_logger.cpp:72:5: error: use of undeclared identifier 'pool'; did you mean 'powl'?
    pool.addAndWaitGroup(runs);
    ^~~~
    powl
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/math.h:444:20: note: 'powl' declared here
extern long double powl(long double, long double);
                   ^
../modules/c++/logging/unittests/test_exception_logger.cpp:72:9: error: member reference base type 'long double (long double, long double)' is not a structure or union
    pool.addAndWaitGroup(runs);
    ~~~~^~~~~~~~~~~~~~~~
9 errors generated.
../modules/c++/tiff/source/FileReader.cpp:68:12: warning: destination for this 'memset' call is a pointer to dynamic class 'Header'; vtable pointer will be overwritten [-Wdynamic-class-memaccess]
    memset(&mHeader, 0, sizeof(mHeader));
    ~~~~~~ ^
../modules/c++/tiff/source/FileReader.cpp:68:12: note: explicitly cast the pointer to silence this warning
    memset(&mHeader, 0, sizeof(mHeader));
           ^
           (void*)

**Comment by asylvest** [comment]
CODA-OSS hasn't been merged into SIX yet... is this happening for you in CODA-OSS master? (still need to merge in the build.py Mac changes... there are one or two-hardcoded things in there we need to generalize).

**Comment by ayoungs** [comment]
I'll review, I've had limited time thus far, my apologies.

**Comment by asylvest** [comment]
OK, everything is merged into SIX master now except for `build.py`.  You shouldn't need to do `--disable-csm` anymore; the build system should automatically turn that off for you.

**Comment by ayoungs** [comment]
Excellent!  I’ll check when I can.

**Comment by ayoungs** [comment]
With the build.py tweaks I see the CSM message, however, when I try to do python was build, see below:
Disabling CSM as it is not supported on this platform
Unsupported platform darwin
$ python waf build
The project was not configured: run "waf configure" first!

**Comment by ayoungs** [comment]
python was configure --disable-csm does work however.

**Comment by ayoungs** [comment]
Build proceeds much farther, still a lingering size_t issue like we've seen in the past.
/Users/andyyoungs/Documents/swdev/six-library-osx/six-library/six/modules/c++/six/include/six/Classification.h:83:5: warning: all paths through this function will call itself [-Winfinite-recursion]
    {
    ^
../six/modules/c++/six/source/NITFWriteControl.cpp:463:43: error: ambiguous conversion for static_cast from 'six::Parameter' to 'size_t' (aka 'unsigned long')
        const size_t optNumRowsPerBlock = static_cast<size_t>(
                                          ^~~~~~~~~~~~~~~~~~~~

**Comment by ayoungs** [comment]
Lines 463,484,740, 826 as well. used sys::Uint32_T. in the past to solve that.

**Comment by ayoungs** [comment]
Changing those final size_t and builds to completion!

**Comment by ayoungs** [comment]
The build.py I'd suggest moving to clang and clang++, to force that I did export CC=clang and CXX=clang++ on the command line.  
Of course other platforms can support clang.
I also get a ton of:
:162:16: warning: private field 'error' is not used [-Wunused-private-field]
    nitf_Error error;
Also trying to figure out how to get rid of:
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]

**Comment by piyushrpt** [comment]
I finally got back to trying to build six on OS X and things seem to build seemlessly now. Closing this pull request. The set of instructions that I followed can be found here: 

https://github.com/piyushrpt/elCapitanSetup/blob/master/sicdSetup.md
